### ISSUE TITLE
Firebase API key is public

### ISSUE THREAD

**Issue by flexwie** [holic/cms#1]
You should maybe think about outsourcing your Firebase API key to a private config file which is not commited to the public repository

**Comment by holic** [comment]
Definitely will. Thanks for the reminder :)

**Comment by flexwie** [comment]
Or you set it as an environement variable

**Comment by holic** [comment]
Done in https://github.com/holic/cms/commit/b160037ea7e92e1d1fefb43316e75924e0f2021f
